### ISSUE TITLE
Add support for multiple spaces

### ISSUE THREAD

**Issue by spuder** [josueespinosa/BingBackground-Mac#1]
Great app. Currently if you use multiple spaces, it only changes the background on the current space. 

It would be nice if it could change all spaces. This looks like a way to do it. 

http://www.addictivetips.com/mac-os/how-to-set-one-wallpaper-for-all-os-x-desktop-spaces-at-once/

Basically this command looks like it will do it. (Where $WLPR is the filename of the wallpaper)

```
 defaults write com.apple.desktop Background “{default = {ImageFilePath=’$WLPR’; };}”; killall Dock
```

**Comment by josueespinosa** [comment]
I can't test this one due to my lack of extra monitors, I would appreciate it if you could verify that my latest commit adds multiple monitor support (it _should_).

**Comment by spuder** [comment]
I'll test this when I am at work and have dual monitors. 

Every monitor can have multiple 'spaces' (or virual desktops). It would be great to change it on every 'space'. 

https://en.wikipedia.org/wiki/Spaces_(software)

Looking at the NSScreen class, I only see one reference to 'Spaces'   'screensHaveSeparateSpaces'.

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSScreen_Class/#//apple_ref/occ/clm/NSScreen/screensHaveSeparateSpaces

**Comment by spuder** [comment]
Confirmed that it does work on multiple monitors. Would still like to see multiple spaces.

**Comment by josueespinosa** [comment]
This functionality isn't well-documented since they changed the way spaces/desktops/backgrounds are managed starting in OS X Mavericks (db file in Application Support instead of standard user defaults), but it looks like it will be possible. I'll push out a commit later tonight.

**Comment by spuder** [comment]
Is there a newer build anywhere? Right now I"m opening xcode and manually compiling every day.

**Comment by josueespinosa** [comment]
I've been busy at college. I did research, and as far as I can tell, there are no  documented ways to change anything other than the current space. Even if you change your background in the settings app, other spaces' backgrounds are not modified. I have a stackoverflow question [here](http://stackoverflow.com/questions/36185506/how-to-loop-through-all-mac-desktop-spaces) regarding this problem that was never answered. Even in sample code provided by Apple found [here](https://developer.apple.com/library/mac/samplecode/DesktopImage/Introduction/Intro.html), they don't update spaces. At the moment, this issue will be inactive until I discover something new or have time to investigate further.

**Comment by josueespinosa** [comment]
Good news, @spuder, it looks like I have found a solution. I pushed the commit to master, let me know if it works for you, then I'll go ahead and close the issue.

**Comment by spuder** [comment]
Awesome. I'm mobile at the moment, so I can't test multiple monitors, however I can test multiple spaces. 

Strangely it only changed 3 of my 4 spaces. 

<img width="1149" alt="screenshot 2016-05-16 10 17 18" src="https://cloud.githubusercontent.com/assets/242382/15295784/68704170-1b4f-11e6-8099-2e358c847b56.png">

**Update** 
Ran a few more times. A split second after BingBackground-Mac changed the background, OS X would change 1 of the 4 spaces back to the maveriks background. 

I had to manually change the background to a different image. The next time BingBackground-Mac ran it changed the background properly.

**Comment by josueespinosa** [comment]
Hmm, very bizarre. Are there any extra details you could provide? Were you on desktop #3 when that occurred? Was that a single time event? Are you running it in Xcode or the executable? I can't seem to reproduce the error.

**Comment by spuder** [comment]
Running using xcode. 
on Desktop 1 when it happened. 
Happened 3 or 4 times, until I changed the background manually on Desktop 3 to something else. 
Desktop 3 has the following programs running (minimized)
- slack
- apple mail
- textual irc
- twitter

I'm also using [total spaces 2](http://totalspaces.binaryage.com/)

Since its likely environmental, or transient, I'll go ahead and close the issue. If it happens with tomorrow's bing background, I"ll open a new issue and link this one.

**Comment by spuder** [comment]
Today all backgrounds updated across all spaces across all monitors. 👍

**Comment by dylib** [comment]
@josueespinosa 

> Good news, @spuder, it looks like I have found a solution.

I just noticed the fix for this, and it works well. How were you able to find the solution?

**Comment by josueespinosa** [comment]
@dylib Someone answered my stackoverflow bounty! You can view it [here](http://stackoverflow.com/a/36882616/1757401). I'm fairly confident this was the first time this specific question was ever asked for the latest MacOS.

**Comment by dylib** [comment]
That is excellent! except it doesn't look like you gave them the bounty - not so excellent.

**Comment by jackwilsdon** [comment]
@dylib: Sadly it looks like they answered it outside of the bounty period of 7 days (assuming @josueespinosa created the bounty 2 days after the question was posted, which is the minimum time for a bounty to be created).
